version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_new
    ports:
      - "5672:5672"      # порт для подключения Spring Boot
      - "15672:15672"    # менеджмент UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: collector
      POSTGRES_USER: collector
      POSTGRES_PASSWORD: collector
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "collector"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: collector-app
    ports:
      - "8080:8080"
    environment:
      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/collector
      SPRING_DATASOURCE_USERNAME: collector
      SPRING_DATASOURCE_PASSWORD: collector
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pg_data:
