server:
  port: 8082

spring:
  application:
    name: collector
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq_broker}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:password}
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: collector-group
      bootstrap-servers: ${BOOTSTRAP_SERVERS:kafka:9092}


app:
  manager:
    url: ${MANAGER_URL:simbirapex.backend.servicemanager}
    port: ${MANAGER_PORT:8081}
  rabbitmq:
    exchange: events.exchange
    queue: events.queue
    routing-key: events.key
